version: '3'
services:
    client:
        container_name: client
        environment:
         - ROS_HOSTNAME=client
         - ROS_MASTER_URI=http://172.20.0.1:11311
        image: cjb873/leorover_demo:1.0
        ports:
         - 8083:8080
        stdin_open: true
        tty: true
